# Generated by Django 2.2.1 on 2019-05-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
